GoatName= input('Who is your goat?')
print ('The goat is'  +  GoatName) 


"""INPUT OUTPUT NEWAR NIYOM-
FIRST E VRIABLE ANNOUNCE KORMU,
 THEN OIVARIABLE ER PORE EQUAL SIGN DIYA INPUT LIKHBO AS INPUT ASK KORA HOBE THEN KON QUES OR INTERPHASE ER JONNO INPUT NEWA HOBE OITA LAGB E.
EKHON PRINT OPTION E OI VARIABLE LIKHLE VARIABLE. 
VARIABLE E COLON HOYNA BUT STRING E COLON HOY TAI DUITA KE PLUS DIYE ALADA KORA HOISE"""